import { Product, Category, TestimonialType } from "./types";

export const featuredCategories: Category[] = [
  {
    id: "1",
    name: "Bibles",
    slug: "bibles",
    description:
      "Explore our wide selection of Bibles in various translations, styles, and formats.",
    image:
      "https://images.pexels.com/photos/267586/pexels-photo-267586.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    featured: true,
  },
  {
    id: "2",
    name: "Devotionals",
    slug: "devotionals",
    description:
      "Daily devotional books to strengthen your faith and spiritual journey.",
    image:
      "https://images.pexels.com/photos/4765691/pexels-photo-4765691.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    featured: true,
  },
  {
    id: "3",
    name: "Fiction",
    slug: "fiction",
    description:
      "Christian fiction for entertainment that aligns with your values.",
    image:
      "https://images.pexels.com/photos/2908984/pexels-photo-2908984.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    featured: true,
  },
  {
    id: "4",
    name: "Children's Books",
    slug: "children",
    description: "Faith-based books that teach and inspire young hearts.",
    image:
      "https://images.pexels.com/photos/256455/pexels-photo-256455.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    featured: true,
  },
];

export const products: Product[] = [
  {
    id: "1",
    slug: "the-purpose-driven-life",
    title: "The Purpose Driven Life",
    author: "Rick Warren",
    price: 14.99,
    originalPrice: 19.99,
    category: "Christian Living",
    format: "Paperback",
    coverImage:
      "https://images.pexels.com/photos/1340588/pexels-photo-1340588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.8,
    reviewCount: 2547,
    description:
      "The Purpose Driven Life is a blueprint for Christian living in the 21st century. This expanded edition features links to videos, assessment tools, and 30 discussion questions to help you find your purpose.",
    shortDescription:
      "Discover your purpose in life with this 40-day spiritual journey.",
    featured: true,
    bestSeller: true,
    inStock: true,
    stockQuantity: 35,
    relatedProducts: ["2", "5", "8"],
    publishDate: "2002-10-23",
    publisher: "Zondervan",
    isbn: "978-0310329060",
    pages: 368,
    language: "English",
    dimensions: "5.5 x 1.1 x 8.4 inches",
  },
  {
    id: "2",
    slug: "mere-christianity",
    title: "Mere Christianity",
    author: "C.S. Lewis",
    price: 11.99,
    originalPrice: 15.99,
    category: "Theology",
    format: "Paperback",
    coverImage:
      "https://images.pexels.com/photos/3693994/pexels-photo-3693994.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.9,
    reviewCount: 1845,
    description:
      "In the classic Mere Christianity, C.S. Lewis, the most important writer of the 20th century, explores the common ground upon which all of those of Christian faith stand together.",
    shortDescription:
      "C.S. Lewis's classic exploration of the foundations of Christian belief.",
    featured: true,
    bestSeller: true,
    inStock: true,
    stockQuantity: 28,
    relatedProducts: ["1", "7", "9"],
    publishDate: "1952-06-01",
    publisher: "HarperOne",
    isbn: "978-0060652920",
    pages: 227,
    language: "English",
    dimensions: "5.3 x 0.6 x 8 inches",
  },
  {
    id: "3",
    slug: "jesus-calling",
    title: "Jesus Calling: Enjoying Peace in His Presence",
    author: "Sarah Young",
    price: 10.99,
    originalPrice: 14.99,
    category: "Devotionals",
    format: "Hardcover",
    coverImage:
      "https://images.pexels.com/photos/2422293/pexels-photo-2422293.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.7,
    reviewCount: 3254,
    description:
      "After many years of writing her own words in her prayer journal, missionary Sarah Young decided to be more attentive to the Savior's voice and begin listening for what He was saying. So with pen in hand, she embarked on a journey that forever changed her—and many others around the world.",
    shortDescription:
      "Devotions for every day of the year with Scripture references.",
    featured: true,
    bestSeller: true,
    inStock: true,
    stockQuantity: 42,
    relatedProducts: ["4", "6", "10"],
    publishDate: "2004-10-10",
    publisher: "Thomas Nelson",
    isbn: "978-1591451884",
    pages: 400,
    language: "English",
    dimensions: "4.7 x 1.1 x 6.5 inches",
  },
  {
    id: "4",
    slug: "niv-study-bible",
    title: "NIV Study Bible, Fully Revised Edition",
    author: "Kenneth L. Barker (Editor)",
    price: 39.99,
    originalPrice: 54.99,
    category: "Bibles",
    subcategory: "Study Bibles",
    format: "Hardcover",
    coverImage:
      "https://images.pexels.com/photos/267703/pexels-photo-267703.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.9,
    reviewCount: 1287,
    description:
      "The NIV Study Bible, Fully Revised Edition has been completely updated for the first time in a decade, with all-new notes, maps, and illustrations. This comprehensive study Bible provides everything you need to gain deeper understanding of God's Word.",
    shortDescription:
      "The bestselling NIV Study Bible, fully revised and updated.",
    featured: true,
    inStock: true,
    stockQuantity: 15,
    relatedProducts: ["5", "12", "15"],
    publishDate: "2020-09-15",
    publisher: "Zondervan",
    isbn: "978-0310448945",
    pages: 2432,
    language: "English",
    dimensions: "6.8 x 2.2 x 9.8 inches",
  },
  {
    id: "5",
    slug: "redeeming-love",
    title: "Redeeming Love",
    author: "Francine Rivers",
    price: 12.99,
    originalPrice: 16.99,
    category: "Fiction",
    format: "Paperback",
    coverImage:
      "https://images.pexels.com/photos/3747139/pexels-photo-3747139.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.8,
    reviewCount: 2165,
    description:
      "California's gold country, 1850. A time when men sold their souls for a bag of gold and women sold their bodies for a place to sleep. Angel expects nothing from men but betrayal. Sold into prostitution as a child, she survives by keeping her hatred alive. And what she hates most are the men who use her, leaving her empty and dead inside.",
    shortDescription:
      "A powerful retelling of the book of Hosea, set during the California Gold Rush.",
    bestSeller: true,
    newRelease: false,
    inStock: true,
    stockQuantity: 23,
    relatedProducts: ["7", "8", "11"],
    publishDate: "2005-05-09",
    publisher: "Multnomah",
    isbn: "978-1590525135",
    pages: 464,
    language: "English",
    dimensions: "5.9 x 1.2 x 9 inches",
  },
  {
    id: "6",
    slug: "the-case-for-christ",
    title: "The Case for Christ",
    author: "Lee Strobel",
    price: 13.99,
    originalPrice: 18.99,
    category: "Apologetics",
    format: "Paperback",
    coverImage:
      "https://images.pexels.com/photos/415071/pexels-photo-415071.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.7,
    reviewCount: 1542,
    description:
      "A seasoned journalist chases down the biggest story in history. The project began as an attempt to disprove the central claim of Christianity. The reporter sifted through medical evidence, psychological evidence, and historical evidence of Jesus' death and resurrection and became a Christian in the process.",
    shortDescription:
      "A journalist's personal investigation of the evidence for Jesus.",
    featured: true,
    inStock: true,
    stockQuantity: 31,
    relatedProducts: ["2", "9", "13"],
    publishDate: "1998-09-01",
    publisher: "Zondervan",
    isbn: "978-0310339304",
    pages: 336,
    language: "English",
    dimensions: "5.5 x 0.9 x 8.5 inches",
  },
  {
    id: "7",
    slug: "the-chronicles-of-narnia",
    title: "The Chronicles of Narnia Box Set",
    author: "C.S. Lewis",
    price: 45.99,
    originalPrice: 65.99,
    category: "Fiction",
    subcategory: "Children",
    format: "Paperback",
    coverImage:
      "https://images.pexels.com/photos/5834/nature-grass-leaf-green.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.9,
    reviewCount: 1875,
    description:
      "Experience all seven tales of C. S. Lewis's classic fantasy series, The Chronicles of Narnia, in one impressive paperback volume. Epic battles between good and evil, fantastic creatures, betrayals, heroic deeds, and friendships won and lost all come together in this unforgettable world.",
    shortDescription:
      "C.S. Lewis's beloved fantasy series in a complete box set.",
    bestSeller: true,
    inStock: true,
    stockQuantity: 18,
    relatedProducts: ["2", "5", "8"],
    publishDate: "2002-10-01",
    publisher: "HarperCollins",
    isbn: "978-0064471190",
    pages: 1728,
    language: "English",
    dimensions: "5.3 x 1.9 x 7.8 inches",
  },
  {
    id: "8",
    slug: "gods-promises-for-your-every-need",
    title: "God's Promises for Your Every Need",
    author: "Jack Countryman",
    price: 9.99,
    originalPrice: 14.99,
    category: "Christian Living",
    format: "Paperback",
    coverImage:
      "https://images.pexels.com/photos/36717/amazing-animal-beautiful-beautifull.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.6,
    reviewCount: 987,
    description:
      "No matter what your situation, God has a promise for you! Life is tough, and there are times when you just need a positive word. Now you can have God's promises at your fingertips with this collection of Scripture arranged by topic to speak directly to your every need.",
    shortDescription:
      "Scriptural promises organized by topic for easy reference.",
    newRelease: true,
    inStock: true,
    stockQuantity: 27,
    relatedProducts: ["1", "3", "10"],
    publishDate: "2018-03-27",
    publisher: "Thomas Nelson",
    isbn: "978-1400323067",
    pages: 320,
    language: "English",
    dimensions: "4.5 x 1 x 6.5 inches",
  },
  {
    id: "12",
    slug: "esv-journaling-bible",
    title: "ESV Single Column Journaling Bible",
    author: "ESV Bibles by Crossway",
    price: 32.99,
    originalPrice: 42.99,
    category: "Bibles",
    subcategory: "Study Bibles",
    format: "Hardcover",
    coverImage:
      "https://images.pexels.com/photos/6373305/pexels-photo-6373305.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.8,
    reviewCount: 856,
    description:
      "The ESV Single Column Journaling Bible is designed to help you create a treasured keepsake of your spiritual journey. With 2-inch ruled margins ideal for writing observations, reflections, prayers, or notes, this Bible makes it easy to engage with Scripture in a deeper way.",
    shortDescription:
      "A Bible designed for note-taking and reflection with wide margins.",
    featured: false,
    bestSeller: true,
    inStock: true,
    stockQuantity: 22,
    relatedProducts: ["4", "15", "19"],
    publishDate: "2018-07-31",
    publisher: "Crossway",
    isbn: "978-1433569074",
    pages: 1360,
    language: "English",
    dimensions: "6.5 x 1.75 x 8.25 inches",
  },
  {
    id: "15",
    slug: "nlt-life-application-bible",
    title: "NLT Life Application Study Bible, Third Edition",
    author: "Tyndale",
    price: 37.99,
    originalPrice: 49.99,
    category: "Bibles",
    subcategory: "Study Bibles",
    format: "Hardcover",
    coverImage:
      "https://images.pexels.com/photos/5946025/pexels-photo-5946025.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.9,
    reviewCount: 1145,
    description:
      "The Life Application Study Bible is today's #1–selling study Bible. The notes not only explain difficult passages and give information on Bible life and times but also go a step further to show you how to apply God's Word to every situation and circumstance of your life.",
    shortDescription:
      "A Bible with notes that help you apply Scripture to everyday life.",
    featured: true,
    newRelease: true,
    inStock: true,
    stockQuantity: 18,
    relatedProducts: ["4", "12", "19"],
    publishDate: "2019-10-01",
    publisher: "Tyndale",
    isbn: "978-1496439345",
    pages: 2272,
    language: "English",
    dimensions: "6.6 x 2.3 x 9.5 inches",
  },
  {
    id: "19",
    slug: "kjv-reference-bible",
    title: "KJV Reference Bible, Center-Column Giant Print",
    author: "Thomas Nelson",
    price: 29.99,
    originalPrice: 39.99,
    category: "Bibles",
    subcategory: "Reference Bibles",
    format: "Leathersoft",
    coverImage:
      "https://images.pexels.com/photos/4050304/pexels-photo-4050304.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4.7,
    reviewCount: 724,
    description:
      "The literary beauty of the King James Version, now in a giant-print format with helpful references and concordance. Enjoy the ease of reading God's Word with this KJV Reference Bible, featuring a giant-print design and center-column references.",
    shortDescription:
      "A classic KJV Bible with giant print for easier reading.",
    featured: false,
    inStock: true,
    stockQuantity: 14,
    relatedProducts: ["4", "12", "15"],
    publishDate: "2017-02-07",
    publisher: "Thomas Nelson",
    isbn: "978-0785215615",
    pages: 1728,
    language: "English",
    dimensions: "6.8 x 1.9 x 9.8 inches",
  },
];

export const testimonials: TestimonialType[] = [
  {
    id: "1",
    name: "Carlos Silva",
    role: "Cliente Fidelizado",
    content:
      "Este e-commerce tem sido minha principal escolha para compras online. O catálogo é diversificado, os preços são competitivos e o atendimento ao cliente é excepcional!",
    image:
      "https://images.pexels.com/photos/3777943/pexels-photo-3777943.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 5,
  },
  {
    id: "2",
    name: "Miguel Fernandes",
    role: "Comprador Frequente",
    content:
      "Encontrei produtos aqui que não consegui encontrar em nenhum outro lugar. Os filtros de busca são eficientes e sempre consigo encontrar exatamente o que procuro.",
    image:
      "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 5,
  },
  {
    id: "3",
    name: "Luísa Rodriguez",
    content:
      "Como uma pessoa ocupada, valorizo a praticidade. As entregas são rápidas, o sistema de devolução é simples e o app da loja é muito intuitivo. Recomendo!",
    image:
      "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    rating: 4,
  },
];
